/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex('Users').del();
  await knex('Users').insert([
    {
      id: 1,
      fullName: 'Violetta Juden',
      email: 'vjuden0@youku.com',
      address: '692 Spaight Avenue',
      zipCode: 1239,
      city: 'Cauday',
      country: 'Peru',
      createdAt: knex.fn.now(),
    },
    {
      id: 2,
      fullName: 'Thorstein Mangeon',
      email: 'tmangeon1@wp.com',
      address: '201 Dottie Court',
      zipCode: 2349,
      city: 'Nemby',
      country: 'Paraguay',
      createdAt: knex.fn.now(),
    },
    {
      id: 3,
      fullName: 'Morgen Allewell',
      email: 'mallewell2@eepurl.com',
      address: '6 Clove Trail',
      zipCode: 3459,
      city: 'Potosí',
      country: 'Colombia',
      createdAt: knex.fn.now(),
    },
    {
      id: 4,
      fullName: 'Erick Fitzpatrick',
      email: 'efitzpatrick3@theguardian.com',
      address: '3752 Granby Terrace',
      zipCode: 4569,
      city: 'Guarapuava',
      country: 'Brazil',
      createdAt: knex.fn.now(),
    },
    {
      id: 5,
      fullName: 'Courtney Borrett',
      email: 'cborrett4@ucoz.ru',
      address: '2 Bluestem Way',
      zipCode: 5679,
      city: 'Villa Nueva',
      country: 'Argentina',
      createdAt: knex.fn.now(),
    },
    {
      id: 6,
      fullName: 'Morley Papps',
      email: 'mpapps5@tiny.cc',
      address: '40580 Old Gate Terrace',
      zipCode: 6789,
      city: 'Cahuacho',
      country: 'Peru',
      createdAt: knex.fn.now(),
    },
    {
      id: 7,
      fullName: 'Annmaria Dalman',
      email: 'adalman6@ovh.net',
      address: '492 Fair Oaks Pass',
      zipCode: 7890,
      city: 'Shanjiao',
      country: 'China',
      createdAt: knex.fn.now(),
    },
    {
      id: 8,
      fullName: 'Pepita Bodham',
      email: 'pbodham7@mysql.com',
      address: '13448 Sullivan Trail',
      zipCode: 8901,
      city: 'Pojok',
      country: 'Indonesia',
      createdAt: knex.fn.now(),
    },
    {
      id: 9,
      fullName: 'Sebastiano Jarmyn',
      email: 'sjarmyn8@bbb.org',
      address: '76 Cottonwood Plaza',
      zipCode: 9021,
      city: 'Bayog',
      country: 'Philippines',
      createdAt: knex.fn.now(),
    },
    {
      id: 10,
      fullName: 'Paxon Ranby',
      email: 'pranby9@earthlink.net',
      address: '712 Mccormick Place',
      zipCode: 1230,
      city: 'Chunoyar',
      country: 'Russia',
      createdAt: knex.fn.now(),
    },
  ]);
};
